name: freex-tts
services:
  indextts:
    container_name: freex-tts
    tty: true
    image: freex-tts:1
    ports:
      - 8066:8066
      - 8060:8060
    # command: ["python", "launch.py"]
    volumes:
      - "D:\\Code\\AI\\index-tts-fastapi:/app"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
